services:
  rabbitmq:
    image: rabbitmq:4-management
    profiles:
      - rabbitmq
      - all
    container_name: shm-rabbitmq
    hostname: shm-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dockerdata/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 5s
  taskservice:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      dockerfile: ./TaskService/Dockerfile
      args:
        GITHUB_OWNER: $GITHUB_PACKAGES_ORGANIZATION
        GITHUB_USERNAME: $GITHUB_PACKAGES_USERNAME
        GITHUB_TOKEN: $GITHUB_PACKAGES_TOKEN
    image: tycho-shm/taskservice
    profiles:
      - services
      - all
    container_name: shm-taskservice
    hostname: shm-taskservice
    ports:
      - 6001:8080
    environment:
      RabbitMQ__Hostname: $RABBITMQ_HOSTNAME
      RabbitMQ__Username: $RABBITMQ_USERNAME
      RabbitMQ__Password: $RABBITMQ_PASSWORD
  notificationservice:
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      dockerfile: ./NotificationService/Dockerfile
      args:
        GITHUB_OWNER: $GITHUB_PACKAGES_ORGANIZATION
        GITHUB_USERNAME: $GITHUB_PACKAGES_USERNAME
        GITHUB_TOKEN: $GITHUB_PACKAGES_TOKEN
    image: tycho-shm/notificationservice
    profiles:
      - services
      - all
    container_name: shm-notificationservice
    hostname: shm-notificationservice
    ports:
      - 6002:8080
    environment:
      RabbitMQ__Hostname: $RABBITMQ_HOSTNAME
      RabbitMQ__Username: $RABBITMQ_USERNAME
      RabbitMQ__Password: $RABBITMQ_PASSWORD