services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: shm-rabbitmq
    hostname: shm-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dockerdata/rabbitmq:/var/lib/rabbitmq