<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Hosting.Abstractions">
        <HintPath>..\..\..\..\.dotnet\shared\Microsoft.AspNetCore.App\9.0.0\Microsoft.Extensions.Hosting.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Clerk.BackendAPI" Version="0.7.2" />
      <PackageReference Include="MailKit" Version="4.12.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.2" />
      <PackageReference Include="shm.messagequeues.abstractions" Version="0.1.0" />
    </ItemGroup>

</Project>
