// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SHM.ProfileService.EfCore;

#nullable disable

namespace SHM.ProfileService.EfCore.Migrations
{
    [DbContext(typeof(ProfileContext))]
    partial class ProfileContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SHM.ProfileService.Model.House.HouseMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HouseProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HouseProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("HouseMemberships");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.House.HouseProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("HouseProfiles");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.Invite.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InvitedUserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitedByUserProfileId");

                    b.HasIndex("InvitedToId");

                    b.HasIndex("InvitedUserProfileId");

                    b.ToTable("Invites");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedDateTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.House.HouseMembership", b =>
                {
                    b.HasOne("SHM.ProfileService.Model.House.HouseProfile", null)
                        .WithMany("Members")
                        .HasForeignKey("HouseProfileId");

                    b.HasOne("SHM.ProfileService.Model.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.House.HouseProfile", b =>
                {
                    b.HasOne("SHM.ProfileService.Model.UserProfile", null)
                        .WithMany("Houses")
                        .HasForeignKey("UserProfileId");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.Invite.Invite", b =>
                {
                    b.HasOne("SHM.ProfileService.Model.UserProfile", "InvitedByUserProfile")
                        .WithMany()
                        .HasForeignKey("InvitedByUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SHM.ProfileService.Model.House.HouseProfile", "InvitedTo")
                        .WithMany()
                        .HasForeignKey("InvitedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SHM.ProfileService.Model.UserProfile", "InvitedUserProfile")
                        .WithMany()
                        .HasForeignKey("InvitedUserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUserProfile");

                    b.Navigation("InvitedTo");

                    b.Navigation("InvitedUserProfile");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.House.HouseProfile", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SHM.ProfileService.Model.UserProfile", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
