apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apigateway/apigateway-deployment.yaml
  - apigateway/apigateway-service.yaml
  - apigateway/apigateway-ocelotjson.yaml
  - profileservice/profileservice-deployment.yaml
  - profileservice/profileservice-service.yaml
  - cloudflared.yaml
  - rabbitmq.yaml