name: Main

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - name: Create and populate .env file
        run: |
          echo "GITHUB_PACKAGES_ORGANIZATION=Tycho-SHM" >> .env
          echo "GITHUB_PACKAGES_USERNAME=Tycho-SHM" >> .env
          echo "GITHUB_PACKAGES_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env

      - name: Docker compose build
        run: |
          docker compose --profile all build
          mkdir dockerimages
          docker save tycho-shm/notificationservice -o ./dockerimages/notificationservice.tar
          docker save tycho-shm/taskservice -o ./dockerimages/taskservice.tar
          docker save tycho-shm/apigateway -o ./dockerimages/apigateway.tar
          docker save tycho-shm/profileservice -o ./dockerimages/profileservice.tar
          docker save tycho-shm/e2etesting -o ./dockerimages/e2etesting.tar

      - name: Upload Docker images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ./dockerimages/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        name: Checkout docker compose file
        with:
          sparse-checkout: |
            docker-compose.yml
            ocelot.json
          sparse-checkout-cone-mode: false

      - name: Create docker images folder
        run: |
          docker images
          mkdir dockerimages

      - name: Download Docker images artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./dockerimages/

      - name: Load Docker images
        run: |
          docker load -i ./dockerimages/notificationservice.tar
          docker load -i ./dockerimages/taskservice.tar
          docker load -i ./dockerimages/apigateway.tar
          docker load -i ./dockerimages/profileservice.tar
          docker load -i ./dockerimages/e2etesting.tar
          docker images

      - name: Create and populate .env file
        run: |
          echo "RABBITMQ_HOSTNAME=rabbitmq" >> .env
          echo "RABBITMQ_USERNAME=guest" >> .env
          echo "RABBITMQ_PASSWORD=guest" >> .env
          echo "MONGODB_USERNAME=testuser" >> .env
          echo "MONGODB_PASSWORD=testpassword" >> .env
          echo "PROFILESERVICEDB_CONNECTIONSTRING=mongodb://testuser:testpassword@mongodb:27017" >> .env
          echo "PROFILESERVICEDB_DATABASE=shm_profileservice" >> .env
          echo "PROFILESERVICEDB_HOUSEPROFILECOLLECTION=houseprofiles" >> .env
          echo "PROFILESERVICEDB_USERPROFILECOLLECTION=userprofiles" >> .env
          echo "CLERK_DOMAIN=${{ secrets.CLERK_DOMAIN }}" >> .env
          echo "TEST_CLERKAPISECRET=${{ secrets.TEST_CLERKAPISECRET }}" >> .env
          echo "TEST_SVIXAUTHTOKEN=${{ secrets.TEST_SVIXAUTHTOKEN }}" >> .env
          echo "TEST_SVIXAPIRUL=${{ secrets.TEST_SVIXAPIRUL }}" >> .env
          echo "TEST_NGROKENDPOINT=willbefetchedautomatically" >> .env
          echo "TEST_NGROK_AUTHTOKEN=${{ secrets.TEST_NGROK_AUTHTOKEN }}" >> .env

      - name: run docker containers
        run: |
          docker compose --profile all --profile testing up --abort-on-container-exit e2etesting

      - name: Parse Trx files
        if: always()
        uses: NasAmin/trx-parser@v0.6.0
        id: trx-parser
        with:
          TRX_PATH: ${{ github.workspace }}/dockerdata/e2etesting/testresults #This should be the path to your TRX files
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push-images:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create docker images folder
        run: |
          docker images
          mkdir dockerimages

      - name: Download Docker images artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ./dockerimages/

      - name: Load Docker images
        run: |
          docker load -i ./dockerimages/notificationservice.tar
          docker load -i ./dockerimages/taskservice.tar
          docker load -i ./dockerimages/apigateway.tar
          docker load -i ./dockerimages/profileservice.tar
          docker images

      - name: Tag docker images
        run: |
          docker tag tycho-shm/notificationservice ghcr.io/tycho-shm/notificationservice:latest
          docker tag tycho-shm/taskservice ghcr.io/tycho-shm/taskservice:latest
          docker tag tycho-shm/apigateway ghcr.io/tycho-shm/apigateway:latest
          docker tag tycho-shm/profileservice ghcr.io/tycho-shm/profileservice:latest

      - name: Push to github packages
        run: |
          docker push ghcr.io/tycho-shm/notificationservice:latest
          docker push ghcr.io/tycho-shm/taskservice:latest
          docker push ghcr.io/tycho-shm/apigateway:latest
          docker push ghcr.io/tycho-shm/profileservice:latest

  cleanup:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
      - push-images
    if: ${{ always() }}

    steps:
      - uses: geekyeggo/delete-artifact@v5
        name: Cleanup artifacts
        with:
          name: |
            docker-images