name: Testing playground

on:
  push:
    branches:
      - github-actions-playground

permissions:
  packages: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - name: build docker compose
        run: docker compose build
