name: Testing playground

on:
  push:
    branches:
      - github-actions-playground

permissions:
  packages: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repo

      - name: Create and populate .env file
        run: |
          echo "RABBITMQ_HOSTNAME=rabbitmq" >> .env
          echo "RABBITMQ_USERNAME=guest" >> .env
          echo "RABBITMQ_PASSWORD=guest" >> .env
          echo "GITHUB_PACKAGES_ORGANIZATION=Tycho-SHM" >> .env
          echo "GITHUB_PACKAGES_USERNAME=Tycho-SHM" >> .env
          echo "GITHUB_PACKAGES_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> .env

      - name: Docker compose build
        run: |
          docker compose --profile rabbitmq --profile services build
          mkdir dockerimages
          docker save tycho-shm/notificationservice -o ./dockerimages/notificationservice.tar
          docker save tycho-shm/taskservice -o ./dockerimages/taskservice.tar

      - name: Upload Docker images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: ./dockerimages/
