apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
resources:
  - ../../base
  - profileservice/profileservice-config.yaml
  - apigateway/apigateway-config.yaml
  - cloudflared-patch.yaml